### ISSUE TITLE
why gorm default logger and your logger need to judge case "sql"

### ISSUE THREAD

**Issue by awkj** [moul/zapgorm#8]
how case not equal "sql" ?

**Comment by moul** [comment]
If you're talking about this switch case -> https://github.com/moul/zapgorm/blob/master/zapgorm.go#L23

It's due to the way gorm is managing its(was) managing its logs with a custom format, see https://github.com/jinzhu/gorm/blob/master/logger.go#L51; Jinzhu was doing a similar switch case approach too
